# template tvae config file

[path_params]
meta_data = "datasets/abalone/abalone.json"
raw_data = "datasets/abalone/abalone.csv"
train_data = "datasets/abalone/train.csv"
val_data = "datasets/abalone/val.csv"
test_data = "datasets/abalone/test.csv"
loss_record = "exp/abalone/tvae/loss.csv"
out_model = "exp/abalone/tvae/tvae.pt"
out_data = "exp/abalone/tvae/abalone.csv"
fidelity_result = "exp/abalone/tvae/fidelity_result.csv"
fidelity_train_result = "exp/abalone/tvae/fidelity_train_result.csv"
privacy_result = "exp/abalone/tvae/privacy_result.csv"
utility_result = "exp/abalone/tvae/utility_result.csv"

[model_params]
epochs = 300
batch_size = 500
l2scale = 1e-5
loss_factor = 2.0
embedding_dim = 128
compress_dims = [128, 128]
decompress_dims = [128, 128]


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data
